/**
 * BackgroundTaskManager — spawn long-running commands so the agent can keep
 * working instead of blocking (tutorial s13).
 *
 * ## Problem
 *
 * When the model calls a bash tool that runs a long command (`npm install`,
 * `docker build`, etc.), the agent loop would normally block waiting for
 * the result.  This wastes time — the model could be doing other work
 * (analyzing output, planning next steps) while the command runs.
 *
 * ## Solution
 *
 * When the model sets `run_in_background: true` on a bash call, the command
 * runs in a **detached child process**.  A placeholder result is returned
 * immediately so the tool-use protocol is satisfied.  When the background
 * task finishes, its output is collected and injected as a notification
 * on the next turn via {@link check}.
 *
 * ## Task lifecycle
 *
 * ```
 * spawn() ──> running ──┬── close(0) ──> done
 *                        └── close(nonzero) / error ──> error
 * ```
 *
 * - **running** — the child process is active.  Output accumulates in
 *   memory via stdout/stderr listeners.
 * - **done** — the process exited with code 0.  Output is available.
 * - **error** — the process exited with a non-zero code or `spawn()`
 *   itself failed.
 *
 * ## Polling mechanism
 *
 * There is no event-driven callback into the agent loop.  Instead, the
 * agent loop periodically calls {@link BackgroundTaskManager.check} to
 * collect any tasks that have completed since the last call.  Completed
 * tasks are drained from the internal `completed` array and returned.
 *
 * ## Why `unref()`?
 *
 * By default, Node keeps running as long as there are active handles
 * (timers, sockets, child processes).  Calling `child.unref()` tells Node
 * not to count this child process when deciding whether to exit.  This
 * means background tasks won't prevent the main process from shutting
 * down — they'll be orphaned if the parent exits first.
 *
 * @module background-tasks
 */

import { spawn } from 'node:child_process';

/**
 * A background task tracked by the manager.
 *
 * Each task corresponds to one spawned child process.  The task persists
 * in `running` until the process exits, then moves to the `completed`
 * list where it stays until {@link BackgroundTaskManager.check} collects it.
 */
export interface BackgroundTask {
  /** Unique background task identifier (generated by the manager). */
  bgId: string;
  /** The original tool-use block ID this background task is associated with. */
  toolUseId: string;
  /** The shell command being executed. */
  command: string;
  /** Current lifecycle status. */
  status: 'running' | 'done' | 'error';
  /** Accumulated stdout + stderr output. */
  output: string;
  /** Unix-epoch-milliseconds timestamp when `spawn()` was called. */
  startTime: number;
}

/** @internal Global counter for generating unique background task IDs. */
let bgCounter = 0;

/**
 * Manages background child processes spawned from tool calls.
 *
 * ## Usage
 *
 * ```ts
 * const bgm = new BackgroundTaskManager();
 *
 * // In the tool handler, when run_in_background is true:
 * const bgId = bgm.spawn('npm install', toolUseId, cwd);
 * // Return placeholder result to model immediately
 *
 * // On each turn of the agent loop:
 * const completed = bgm.check();
 * for (const task of completed) {
 *   // Inject output as a tool result notification
 * }
 * ```
 *
 * ## Platform support
 *
 * Uses `cmd.exe /c` on Windows, `/bin/bash -c` elsewhere.  This is
 * consistent with the bash tool itself.
 *
 * ## Memory considerations
 *
 * Command output accumulates in memory as a string.  For commands that
 * produce gigabytes of output, this will cause memory pressure.  Consider
 * truncating output or streaming to a file for very large commands.
 */
export class BackgroundTaskManager {
  /** Currently running tasks, keyed by `bgId`. */
  private running = new Map<string, BackgroundTask>();

  /** Tasks that have completed but not yet collected via `check()`. */
  private completed: BackgroundTask[] = [];

  /**
   * Start a command in the background.
   *
   * Spawns a detached child process with piped stdio.  Output is
   * accumulated as the process runs.  The child is `unref()`-ed so
   * it does not prevent the parent process from exiting.
   *
   * @param command - Shell command string to execute.
   * @param toolUseId - The tool-use block ID this task corresponds to.
   * @param cwd - Working directory for the child process.
   * @returns The generated background task ID (`bgId`).
   *
   * @example
   * ```ts
   * const bgId = mgr.spawn('npm run build', 'toolu_abc123', '/project');
   * // Immediately return placeholder to model:
   * return { type: 'tool_result', tool_use_id: 'toolu_abc123',
   *          content: `Running in background (bgId: ${bgId})...` };
   * ```
   */
  spawn(command: string, toolUseId: string, cwd: string): string {
    bgCounter += 1;
    const bgId = `bg_${String(bgCounter).padStart(4, '0')}`;
    const task: BackgroundTask = {
      bgId,
      toolUseId,
      command,
      status: 'running',
      output: '',
      startTime: Date.now(),
    };
    this.running.set(bgId, task);

    const shell = process.platform === 'win32' ? 'cmd.exe' : '/bin/bash';
    const flag = process.platform === 'win32' ? '/c' : '-c';
    const child = spawn(shell, [flag, command], { cwd, detached: true, stdio: 'pipe' });
    let out = '';
    // Accumulate stdout and stderr into a single output string.
    child.stdout.on('data', (d: Buffer) => (out += d.toString()));
    child.stderr.on('data', (d: Buffer) => (out += d.toString()));
    child.on('close', (code) => {
      // Append exit code info for non-zero exits.
      if (code) out += `\n[exit ${code}]`;
      task.output = out;
      task.status = code === 0 ? 'done' : 'error';
      // Move from running to completed.
      this.running.delete(bgId);
      this.completed.push(task);
    });
    child.on('error', (err) => {
      // The spawn itself failed (e.g. command not found).
      task.output = `Error: ${err.message}`;
      task.status = 'error';
      this.running.delete(bgId);
      this.completed.push(task);
    });
    // Don't wait for the child — unref so it doesn't keep the process alive.
    child.unref();

    return bgId;
  }

  /**
   * Collect completed background tasks since the last check.
   *
   * This is a **draining** read: once collected, tasks are removed from
   * the internal buffer.  Call this once per turn of the agent loop to
   * get any newly finished tasks.
   *
   * @returns Array of completed {@link BackgroundTask} objects (empty if none).
   */
  check(): BackgroundTask[] {
    const ready = this.completed.splice(0);
    return ready;
  }

  /**
   * How many tasks are still running?
   *
   * Useful for status reporting — the agent can tell the model how many
   * background tasks are outstanding.
   */
  get pendingCount(): number {
    return this.running.size;
  }
}

/**
 * Heuristic: should this command be run in the background?
 *
 * Checks the command string against a keyword list of known slow operations
 * (package managers, build tools, test runners, compilers).  This is a
 * best-effort guess — the model can always override by explicitly setting
 * `run_in_background`.
 *
 * @param toolInput - The tool-use input object (must have a `command` string field).
 * @returns `true` if the command matches a known slow operation pattern.
 *
 * @example
 * ```ts
 * isSlowOperation({ command: 'npm install' });     // true
 * isSlowOperation({ command: 'pip install torch' }); // true
 * isSlowOperation({ command: 'echo hello' });        // false
 * ```
 */
export function isSlowOperation(toolInput: Record<string, unknown>): boolean {
  const cmd = String(toolInput.command ?? '').toLowerCase();
  const keywords = [
    'install', 'build', 'test', 'deploy', 'compile',
    'docker build', 'pip install', 'npm install',
    'cargo build', 'pytest', 'make',
  ];
  return keywords.some((kw) => cmd.includes(kw));
}
